services:
  mongo:
    image: mongo
    restart: always
    container_name: myMongoInstance
    ports: 
      - 27019:27017
    volumes:
      - mongo-data:/data/db

  backend:
    image: takudan03/tol-backend
    depends_on:
      - mongo
    ports:
      - 9000:9000
    environment:
      - DEBUG=True
    build: .
  
  frontend:
    image: takudan03/tol-frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      - DEBUG=True
    build: .

volumes:
  mongo-data:
    driver: local